In [1]:
remotes::install_github("kjhealy/covdata")

Downloading GitHub repo kjhealy/covdata@master

✔  checking for file ‘/tmp/RtmpkGqcBT/remotesd3419e9da/kjhealy-covdata-4a97981/DESCRIPTION’
─  preparing ‘covdata’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘covdata_0.0.0.9000.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
library(covdata)
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──

✔ ggplot2 3.3.0.9000     ✔ purrr   0.3.3
✔ tibble  2.1.3          ✔ dplyr   0.8.4
✔ tidyr   1.0.2          ✔ stringr 1.4.0
✔ readr   1.3.1          ✔ forcats 0.4.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [3]:
covnat

     date       cname                             iso3 cases deaths pop_2018
1    2019-12-31 Afghanistan                       AFG   0    0        37172386
2    2019-12-31 Algeria                           DZA   0    0        42228429
3    2019-12-31 Armenia                           ARM   0    0         2951776
4    2019-12-31 Australia                         AUS   0    0        24992369
5    2019-12-31 Austria                           AUT   0    0         8847037
6    2019-12-31 Azerbaijan                        AZE   0    0         9942334
7    2019-12-31 Bahrain                           BHR   0    0         1569439
8    2019-12-31 Belarus                           BLR   0    0         9485386
9    2019-12-31 Belgium                           BEL   0    0        11422068
10   2019-12-31 Brazil                            BRA   0    0       209469333
11   2019-12-31 Cambodia                          KHM   0    0        16249798
12   2019-12-31 Canada                            CAN   0    0        37058856
13   2019-12-31 China                             CHN  27    0      1392730000
14   2019-12-31 Croatia                           HRV   0    0         4089400
15   2019-12-31 Czech Republic                    CZE   0    0              NA
16   2019-12-31 Denmark                           DNK   0    0         5797446
17   2019-12-31 Dominican Republic                DOM   0    0        10627165
18   2019-12-31 Ecuador                           ECU   0    0        17084357
19   2019-12-31 Egypt                             EGY   0    0        98423595
20   2019-12-31 Estonia                           EST   0    0         1320884
21   2019-12-31 Finland                           FIN   0    0         5518050
22   2019-12-31 France                            FRA   0    0        66987244
23   2019-12-31 Georgia                           GEO   0    0         3731000
24   2019-12-31 Germany                           DEU   0    0        82927922
25   2019-12-31 Greece                            GRC   0    0        10727668
26   2019-12-31 Iceland                           ISL   0    0          353574
27   2019-12-31 India                             IND   0    0      1352617328
28   2019-12-31 Indonesia                         IDN   0    0       267663435
29   2019-12-31 Iran, Islamic Republic of         IRN   0    0        81800269
30   2019-12-31 Iraq                              IRQ   0    0        38433600
⋮    ⋮          ⋮                                 ⋮    ⋮     ⋮      ⋮
9829 2020-04-10 South Sudan                       SSD      0    0    10975920
9830 2020-04-10 Spain                             ESP   5756  683    46723749
9831 2020-04-10 Sri Lanka                         LKA      1    0    21670000
9832 2020-04-10 Sudan                             SDN      0    0    41801533
9833 2020-04-10 Suriname                          SUR      0    0      575991
9834 2020-04-10 Sweden                            SWE    722  106    10183175
9835 2020-04-10 Switzerland                       CHE    785   51     8516543
9836 2020-04-10 Syrian Arab Republic              SYR      0    0    16906283
9837 2020-04-10 Taiwan, Province of China         TWN      1    0    23780452
9838 2020-04-10 Thailand                          THA     50    1    69428524
9839 2020-04-10 Timor-Leste                       TLS      1    0     1267972
9840 2020-04-10 Togo                              TGO      3    0     7889094
9841 2020-04-10 Trinidad and Tobago               TTO      2    0     1389858
9842 2020-04-10 Tunisia                           TUN     20    2    11565204
9843 2020-04-10 Turkey                            TUR   4056   96    82319724
9844 2020-04-10 Turks and Caicos Islands          TCA      0    0       31458
9845 2020-04-10 Uganda                            UGA      0    0    42723139
9846 2020-04-10 Ukraine                           UKR    224    5    44622516
9847 2020-04-10 United Arab Emirates              ARE    331    2     9630959
9848 2020-04-10 United Kingdom                    GBR   4344  881    66488991
9849 2020-04-10 Tanzania, United Republic of      TZA      0    0    56318348
9850 2020-04-10 United States                     USA  33901 1873   327167434
9851 2020-04-10 Virgin Islands, U.S.              VIR      5    0      106977
9852 2020-04-10 Uruguay                           URY     17    0     3449299
9853 2020-04-10 Uzbekistan                        UZB     27    0    32955400
9854 2020-04-10 Venezuela, Bolivarian Republic of VEN      4    1    28870195
9855 2020-04-10 Viet Nam                          VNM      4    0    95540395
9856 2020-04-10 Yemen                             YEM      1    0    28498687
9857 2020-04-10 Zambia                            ZMB      0    0    17351822
9858 2020-04-10 Zimbabwe                          ZWE      0    1    14439018
     cu_cases cu_deaths
1     0       0
2     0       0
3     0       0
4     0       0
5     0       0
6     0       0
7     0       0
8     0       0
9     0       0
10    0       0
11    0       0
12    0       0
13   27       0
14    0       0
15    0       0
16    0       0
17    0       0
18    0       0
19    0       0
20    0       0
21    0       0
22    0       0
23    0       0
24    0       0
25    0       0
26    0       0
27    0       0
28    0       0
29    0       0
30    0       0
⋮    ⋮        ⋮
9829      2       0
9830 152446   15238
9831    190       7
9832     14       2
9833     10       1
9834   9141     793
9835  23495     756
9836     19       2
9837    380       5
9838   2473      33
9839      2       0
9840     73       3
9841    109       8
9842    643      25
9843  42282     908
9844      8       1
9845     53       0
9846   1892      57
9847   2990      14
9848  65077    7978
9849     25       1
9850 466033   16690
9851     50       1
9852    473       7
9853    582       3
9854    171       9
9855    255       0
9856      1       0
9857     39       1
9858     11       3

In [4]:
covnat<- covnat %>% arrange (cname, date) %>% filter (cu_cases>0)

In [ ]:
#We get the first day for each country
min_day_per_country<- aggregate.data.frame(covnat$date,
                by = list(covnat$cname),
                FUN = min)
#we rename the columns
colnames(min_day_per_country) <- c("cname","first_day")

In [ ]:
covnat<- merge(covnat, min_day_per_country, by='cname' )

In [ ]:
covnat<- covnat  %>%  mutate (days=as.integer( date-first_day))

In [ ]:
plot(covnat[covnat$cname=='Argentina',]$days, covnat[covnat$cname=='Argentina',]$cu_cases, type='l', col='blue', main='Cumulative cases by country', xlab='Number of days', ylab='Number of cases', xlim=c(0,90), ylim=c(0,150000) )

lines(covnat[covnat$cname=='Spain',]$days, covnat[covnat$cname=='Spain',]$cu_cases, col='red')

lines(covnat[covnat$cname=='Italy',]$days, covnat[covnat$cname=='Italy',]$cu_cases, col='lightblue')

lines(covnat[covnat$cname=='Brazil',]$days, covnat[covnat$cname=='Brazil',]$cu_cases, col='darkgreen')

legend("topleft", 
  legend = c('Argentina', 'Spain', 'Italy', 'Brazil'),
  fill =c('blue', 'red', 'lightblue', 'darkgreen'),
    col=c('blue', 'red', 'lightblue', 'darkgreen'),
        bty='n')

In [ ]:
plot(covnat[covnat$cname=='Argentina',]$days, log(covnat[covnat$cname=='Argentina',]$cu_cases), type='l', col='blue', main='Cumulative cases by country in log scale', xlab='Number of days', ylab='Number of cases in log scale', xlim=c(0,90), ylim=c(0,12) )

lines(covnat[covnat$cname=='Spain',]$days, log(covnat[covnat$cname=='Spain',]$cu_cases), col='red')

lines(covnat[covnat$cname=='Italy',]$days, log(covnat[covnat$cname=='Italy',]$cu_cases), col='lightblue')

lines(covnat[covnat$cname=='Brazil',]$days, log(covnat[covnat$cname=='Brazil',]$cu_cases), col='darkgreen')

legend("topleft", 
  legend = c('Argentina', 'Spain', 'Italy', 'Brazil'),
  fill =c('blue', 'red', 'lightblue', 'darkgreen'),
    col=c('blue', 'red', 'lightblue', 'darkgreen'),
        bty='n')